#!/bin/bash/

Instances=("mongodb" "mysql" "frontend" "user")

for instance in ${Instances[@]}
do
Instance_ID=$(aws ec2 run-instances --image-id ami-09c813fb71547fc4f --instance-type t2.micro --security-group-ids sg-07317f8f22fc5bd9f --tag-specifications ResourceType=instance,Tags=[{Key=Name, Value=$instance}] --query "Instances[0].InstanceId" --output text)

if [ $instance != "frontend" ]
then
   IP=$(aws ec2 describe-instances --instance-ids $Instance_ID --query "Reservations[0].Instances[0].PrivateIpAddress" --output text)
 
else
   IP=$(aws ec2 describe-instances --instance-ids $Instance_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
fi
echo " $instance instance IP address: $IP "
done